In [ ]:
#Perform Practical based on word embedding.
#one-hot encoding

from tensorflow.keras.utils import to_categorical
class_names = ['Airplane','Automobile','Bird','Cat','Deer','Dog','Frog','Horse','Ship','Truck']
n=enumerate(class_names)
one_hot_embedding=[]
for i, word in n:
  print(i, word)
  one_hot_embedding = to_categorical(i, 10)
  print(one_hot_embedding)

0 Airplane
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1 Automobile
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
2 Bird
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
3 Cat
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
4 Deer
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
5 Dog
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
6 Frog
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
7 Horse
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
8 Ship
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
9 Truck
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [12]:
#Perform practical based on back propagation learning algorithm
#implementing ex-or problem using backpropagation

import numpy as np

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        self.weights_input_hidden = np.random.randn(self.input_size, self.hidden_size)
        self.weights_hidden_output = np.random.randn(self.hidden_size, self.output_size)
        self.bias_hidden = np.zeros((1, self.hidden_size))
        self.bias_output = np.zeros((1, self.output_size))

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def feedforward(self, X):
        self.hidden_activation = np.dot(X, self.weights_input_hidden) + self.bias_hidden
        self.hidden_output = self.sigmoid(self.hidden_activation)
        self.output_activation = np.dot(self.hidden_output, self.weights_hidden_output) + self.bias_output
        self.predicted_output = self.sigmoid(self.output_activation)
        return self.predicted_output

    def backward(self, X, y, learning_rate):
        output_error = y - self.predicted_output
        output_delta = output_error * self.sigmoid_derivative(self.predicted_output)
        hidden_error = np.dot(output_delta, self.weights_hidden_output.T)
        hidden_delta = hidden_error * self.sigmoid_derivative(self.hidden_output)
        self.weights_hidden_output += np.dot(self.hidden_output.T, output_delta) * learning_rate
        self.bias_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate
        self.weights_input_hidden += np.dot(X.T, hidden_delta) * learning_rate
        self.bias_hidden += np.sum(hidden_delta, axis=0, keepdims=True) * learning_rate

    def train(self, X, y, epochs, learning_rate):
        for epoch in range(epochs):
            output = self.feedforward(X)
            self.backward(X, y, learning_rate)
            if epoch % 100 == 0:
                loss = np.mean(np.square(y - output))
                print(f"Epoch {epoch}, Loss:{loss}")

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

nn = NeuralNetwork(input_size=2, hidden_size=4, output_size=1)
nn.train(X, y, epochs=1000, learning_rate=0.1)

output = nn.feedforward(X)
print("Predictions after training:")
print(output)


Epoch 0, Loss:0.2744660978829988
Epoch 100, Loss:0.2398715860000168
Epoch 200, Loss:0.2370095635796753
Epoch 300, Loss:0.23376358810501174
Epoch 400, Loss:0.23014208721110274
Epoch 500, Loss:0.22617856427622662
Epoch 600, Loss:0.22192430805076568
Epoch 700, Loss:0.21744308771917903
Epoch 800, Loss:0.2128053652362557
Epoch 900, Loss:0.20808000240121893
Predictions after training:
[[0.28172804]
 [0.57003629]
 [0.59833253]
 [0.62266899]]
